paths:
  /api/products/:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: Products obtained correctly
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/Product'
        "401":
          description: Missing permissions to get products
        "500":
          description: Server Error.
  /api/products/{pid}:
    get:
      summary: Get product by ID.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: pid is the ID of the product wanted.
          schema:
            $type: string
      responses:
        "200":
          description: Product obtained correctly
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/Product'
        "401":
          description: Missing permissions to get products
        "500":
          description: Server Error.
    put:
      summary: Put product by ID.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: pid is the ID of the product wanted.
          schema:
            $type: string
      requestedBody:
        required: true
        content:
        application/json:
          schema:
            $ref: '#components/requestedBodies/updateProduct'
      responses:
        "200":
          description: Product updated correctly
          content:
            application/json:
              schema: 
                $ref: '#components/schemas/Product'
        "401":
          description: Missing permissions to get products
        "500":
          description: Server Error.

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: ObjectId
          description: Autogenerated product ID.
        title: 
          type: String
          required: true
          description: Name/Title of Product.
        description:
          type: String
          required: true
          description: Description of Product.
        code:
          type: String
          unique: true
          required: true
          description: Code of Product.
        price: 
          type: Number
          required: true
          description: Price of Product.
        status: 
          type: Boolean
          description: Status of Product.
        stock: 
          type: Number
          description: Stock of Product.   
        thumbnails: 
          type: Array
          description: Images of Product.
      example:
        id: ObjectId(`jsdcf78ve8veew7rcwr3`)
        title: Product 1
        description: Description of Product 1
        code: 100
        price: 100.00
        status: true
        stock: 100
        thumbnails: []